"""initial schema

Revision ID: 0e2207548c4f
Revises: 
Create Date: 2026-08-04 18:00:29.034121
"""
from alembic import op
import sqlalchemy as sa


revision = '0e2207548c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('predicted_tmin_c', sa.Float(), nullable=False),
    sa.Column('alarm_fired', sa.Boolean(), nullable=False),
    sa.Column('alarm_threshold_c', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('cutoff_ts', sa.String(length=32), nullable=False),
    sa.Column('snapshot_ts', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station', 'date', name='uq_forecast_station_date')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_forecasts_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_station'), ['station'], unique=False)

    op.create_table('station_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('forecast_stored', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=256), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station', 'date', name='uq_run_station_date')
    )
    with op.batch_alter_table('station_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_runs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_runs_station'), ['station'], unique=False)

    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('threshold_c', sa.Float(), nullable=False),
    sa.Column('pending_mode', sa.String(length=16), nullable=True),
    sa.Column('pending_threshold_c', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verify_code_hash', sa.String(length=64), nullable=True),
    sa.Column('verify_attempts', sa.Integer(), nullable=False),
    sa.Column('verify_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sms_at', sa.DateTime(timezone=True), nullable=True),
    # true()/false() compile to `true`/`false` on Postgres and `1`/`0` on SQLite;
    # a bare text('1')/text('0') is rejected as an integer default on a Postgres
    # boolean column (the whole point of the D1 fix).
    sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('confirm_sms_pending', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'station', name='uq_sub_phone_station')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_station'), ['station'], unique=False)

    op.create_table('sent_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=256), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'forecast_date', name='uq_sent_sub_date')
    )
    with op.batch_alter_table('sent_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sent_notifications_subscriber_id'), ['subscriber_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sent_notifications_subscriber_id'))

    op.drop_table('sent_notifications')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_station'))
        batch_op.drop_index(batch_op.f('ix_subscribers_phone'))

    op.drop_table('subscribers')
    with op.batch_alter_table('station_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_runs_station'))
        batch_op.drop_index(batch_op.f('ix_station_runs_date'))

    op.drop_table('station_runs')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_station'))
        batch_op.drop_index('ix_forecasts_date')

    op.drop_table('forecasts')
    # ### end Alembic commands ###
